### ISSUE TITLE
How I can exclude special characters

### ISSUE THREAD

**Issue by sonomirco** [thehanimo/pr-title-checker#13]
Hi,
I would like to check that the title doesn't have any special character, but if I pass the regexp of this type the action files `[<>'"/;`%]`

**Comment by thehanimo** [comment]
Hey @sonomirco! I'm assuming that you're trying to prevent any of `<`, `>`, `'`, `"`, `/`, `;`, `` ` ``, or `%`, anywhere in the title.
This should be the regexp you're looking for:
```json
"regexp": "^[^<>\\'\\\"/;\\`%]*$"
```

**Comment by sonomirco** [comment]
Thanks I'll try it :)

**Comment by sonomirco** [comment]
All good thanks.
