### ISSUE TITLE
Ignore PRs label

### ISSUE THREAD

**Issue by Seluj78** [thehanimo/pr-title-checker#2]
Hi ! I'm about to setup your action in our repo (https://github.com/python/python-docs-fr) and I would like to know if it would be possible to add a config where you could specify one or more labels to be ignored by your check. For example, in our case it would be `meta`

Cheers !

**Comment by thehanimo** [comment]
Hey @Seluj78! I just released a new version (v1.2) supporting this. Make sure you update your `.github/workflows/pr-title-cheker.yml` file to use v1.2. Also include `labeled` and `unlabeled` to the `types` field in the same file (Refer to the updated README file in case you need more info). Hope it helps you manage pull requests more efficiently.

Thank you so much for the suggestion!

**Comment by Seluj78** [comment]
Wow thank you so much for your reactivity ! really appreciated ! I'll update my PR now (https://github.com/python/python-docs-fr/pull/1472) and let you know if everything works, and i'll let you know if I have any other suggestions

You rock 🚀

**Comment by Seluj78** [comment]
I tried to add you as a co author but I didn't have your email 🤷‍♂️ [`f5c293c` (#1472)](https://github.com/python/python-docs-fr/pull/1472/commits/f5c293c04644762f64262f40a97297d3c00f538d)

**Comment by thehanimo** [comment]
hani.m17@iiits.in :)
