### ISSUE TITLE
Couldn't retrieve the config file specified - HttpError: Not Found

### ISSUE THREAD

**Issue by EliasSalom** [thehanimo/pr-title-checker#26]
i have been trying to use this tool but I receive this issue all the time
this is my `JSON` file
```sh
{
    "LABEL": {
      "name": "title needs formatting",
      "color": "EEEEEE"
    },
    "CHECKS": {
      "prefixes": ["fix: ", "feat: ", "docs: ", "chore: ", "style: ", "refactor: ", "perf: ", "test: ", "revert: "],
      "regexp": "docs\\(v[0-9]\\): ",
      "regexpFlags": "i",
      "ignoreLabels" : ["dont-check-PRs-with-this-label", "meta"]
    },
    "MESSAGES": {
      "success": "All OK",
      "failure": "Please fix the following issues:",
      "notice": ""
    }
  }
```

and this is my `yml` file
```sh
name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: "./pr-title-checker-config.json"
```

**Comment by EliasSalom** [comment]
my root is like that's, `.github/workflows/pr-title-checker-config.json`

**Comment by EliasSalom** [comment]
![Screen Shot 2022-07-13 at 6 23 13 PM](https://user-images.githubusercontent.com/39850311/178757696-3e51ee1f-90d2-4da3-a5da-d7d1e95e9f9e.png)

**Comment by thehanimo** [comment]
Are you sure you're using `configuration_path: ".github/workflows/pr-title-checker-config.json"`? Is this a public repository you're working on?

**Comment by EliasSalom** [comment]
https://github.com/Fullstack-Alfanar/github-action-test/pull/3

please check

**Comment by thehanimo** [comment]
Thanks, please check your [pr-title-checker.yml](https://github.com/Fullstack-Alfanar/github-action-test/blob/develop/.github/workflows/pr-title-checker.yml) file. Update it to contain `configuration_path: ".github/workflows/pr-title-checker-config.json"`

**Comment by thehanimo** [comment]
Although you have updated it in your non-default branches, the configuration file for the workflow is taken from your default branch, which still contains the old configuration path. You'll have to update this field in your default branch.

**Comment by EliasSalom** [comment]
you check the develop, please check the PR 
https://github.com/Fullstack-Alfanar/github-action-test/blob/feat/new-feat/.github/workflows/pr-title-checker.yml
this one

**Comment by EliasSalom** [comment]
**yes sir it's work now,** please mention this on the `README` 
I think there are a lot of developers who will fall in this!
and also put they need to put all the following root-like `configuration_path: ".github/workflows/pr-title-checker-config.json"`

**Comment by Canato** [comment]
So we need to merge the `json` file before we can run the CI? So we cannot test before merge the json, correct?

Thanks!

**Comment by thehanimo** [comment]
That is correct yes.

Also, you might wanna look at #28. Once we get url support, you could always update the file at the given url and not worry about merging branches and stuff.
