### ISSUE TITLE
Configuration file outside the repo

### ISSUE THREAD

**Issue by dave-v** [thehanimo/pr-title-checker#28]
We would like to use this action on many different repos with the same configuration, so it would be nice to define the configuration in a common location and reuse it.

An example is this action: https://github.com/release-drafter/release-drafter#configuration-options (look at the paragraph after the table of options that mentions Probot config).
In that case, we are able to put configuration files in a separate repo, and each repo using the action can get its config from there.

Perhaps a simple way could be to allow the `configuration_path` to accept a URL returning the configuration, or for private repos, providing the repo and filepath in that repo, an appropriate access token, and using the GitHub API to extract file contents.

If you would accept a PR, I might have a go.

**Comment by thehanimo** [comment]
That definitely seems like a nice feature to have! I like the `configuration_path`-being-a-URL approach which will essentially be a public URL. About private repos, would a parameter like `is_private` or even better, a `key` along with the URL help?

So this way, there will be 3 types of paths to config files:
1. Relative to current repo
2. Absolute public URLs
3. Absolute private URLs (with a flag/key)


Also, PRs are always welcome :)

**Comment by dave-v** [comment]
I will do some experimenting... but probably quite slowly 🙂.

**Comment by rjulius23** [comment]
Isnt it an option to make the GITHUB_REPOSITORY an input variable ? That way you can specify your tempalte repository where your workflow templates are.

**Comment by Noamshmueli** [comment]
+1

**Comment by alexschwartz** [comment]
+1 

I am trying to use this action as an organization wide required action. And it always look for the config file in the wrong location

**Comment by thehanimo** [comment]
I'll treat this as high priority. PRs welcome :)

**Comment by smzelek** [comment]
@dave-v 
@thehanimo 
I unintentionally made a PR that partially addresses this issue:
https://github.com/thehanimo/pr-title-checker/pull/36

in this PR you can provide a local filepath to your configuration (we needed shared configuration across all our repos)

**Comment by thehanimo** [comment]
@alexschwartz @dave-v @Noamshmueli @rjulius23 more ways to specify config file is now supported in [v1.4.0](https://github.com/thehanimo/pr-title-checker/releases/tag/v1.4.0)
