### ISSUE TITLE
Node 12 deprecation warning

### ISSUE THREAD

**Issue by jcw-** [thehanimo/pr-title-checker#29]
Seeing this on warning in GitHub when using this action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: thehanimo/pr-title-checker

According to that link, looks like the deadline is "Summer 2023".

**Comment by thehanimo** [comment]
Released [v1.3.5](https://github.com/thehanimo/pr-title-checker/releases/tag/v1.3.5)!
