### ISSUE TITLE
PR Title checkers create runs and ignores the meta label set

### ISSUE THREAD

**Issue by Seluj78** [thehanimo/pr-title-checker#3]
![Screenshot 2020-12-03 at 10 46 52](https://user-images.githubusercontent.com/4641317/100994169-9b116480-3556-11eb-9332-4db6ca3f5088.png)

**Comment by Seluj78** [comment]
https://github.com/python/python-docs-fr/pull/1496

**Comment by thehanimo** [comment]
I need more details. Unable to find the tests in that PR. Could you send a link to the console?

**Comment by Seluj78** [comment]
What do you mean by console ?

**Comment by Seluj78** [comment]
Oh like the GitHub actions console ? I just looked and it is not here anymore, weird :/

**Comment by Seluj78** [comment]
Sorry I cannot give you more details, you can close the issue if you want :) I didn't fully understand what was happening either :/

**Comment by thehanimo** [comment]
Sure no problem. Let me know if you need any help!
