### ISSUE TITLE
Deprecation warning in GitHub CI

### ISSUE THREAD

**Issue by mnojek** [thehanimo/pr-title-checker#32]
Hey, thanks for this great tool!
I just integrated it into my project and I am playing with it a bit.

I noticed that for each run in the GitHub CI, it returns a deprecation warning for `Buffer()` method.
Full output below:

```
(node:1568) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

The only place in the codebase when it is used is probably [here](https://github.com/thehanimo/pr-title-checker/blob/e914bff8ab5e6f1a6a270da6954cd6bfd1d7f1fb/index.js#L146). Would be great to fix it and make the warning disappear.
Regards!

**Comment by NicoMarksman** [comment]
Hi,
I'm getting the same error. 

```
Error: Couldn't retrieve or parse the config file specified - HttpError: Not Found
```

I also get an error here
```
Error: Couldn't retrieve or parse the config file specified - HttpError: Not Found
```

<img width="411" alt="Screenshot 2023-02-07 at 9 33 15 PM" src="https://user-images.githubusercontent.com/60318513/217358680-07281888-9bdd-407d-904d-79945472d576.png">

json:
```json
{
  "LABEL": {
    "name": "title needs formatting",
    "color": "EEEEEE"
  },
  "CHECKS": {
    "prefixes": ["fix: ", "feat: "],
    "regexp": "docs\\(v[0-9]\\): ",
    "regexpFlags": "i",
    "ignoreLabels" : ["dont-check-PRs-with-this-label", "meta"]
  },
  "MESSAGES": {
    "success": "All OK",
    "failure": "Failing CI test",
    "notice": ""
  }
}
```

**Comment by thehanimo** [comment]
@NicoMarksman your `configuration_path` in `.github/workflows/pr-title-checker.yml` is `.github/pr-title-checker-config.json` by default.

Either change that to `.github/workflows/pr-title-checker-config.json`
OR
move your `pr-title-checker-config.json` to `.github/` from `.github/workflows/`

**Comment by thehanimo** [comment]
@mnojek this seems to be caused by dependencies that are still using `new Buffer()`  :/

Do you think suppressing this warning would be a good idea so that the output log is more readable?

**Comment by thehanimo** [comment]
Released [v1.3.7](https://github.com/thehanimo/pr-title-checker/releases/tag/v1.3.7)!

**Comment by NicoMarksman** [comment]
That's awesome @thehanimo ! :)

**Comment by NicoMarksman** [comment]
> @NicoMarksman your `configuration_path` in `.github/workflows/pr-title-checker.yml` is `.github/pr-title-checker-config.json` by default.
> 
> Either change that to `.github/workflows/pr-title-checker-config.json` OR move your `pr-title-checker-config.json` to `.github/` from `.github/workflows/`
So I should move `pr-title-checker-config.json` to `.github/pr-title-checker-config.json`?

**Comment by thehanimo** [comment]
> > @NicoMarksman your `configuration_path` in `.github/workflows/pr-title-checker.yml` is `.github/pr-title-checker-config.json` by default.
> > Either change that to `.github/workflows/pr-title-checker-config.json` OR move your `pr-title-checker-config.json` to `.github/` from `.github/workflows/`
> 
> So I should move `pr-title-checker-config.json` to `.github/pr-title-checker-config.json`?

Yes

**Comment by mnojek** [comment]
Thanks @thehanimo! 🙇🏻  I will update the tool and start using it :)
