### ISSUE TITLE
Allow to fail the CI without adding any labels

### ISSUE THREAD

**Issue by VincentLanglet** [thehanimo/pr-title-checker#33]
Hi @jcw- @thehanimo 

I wanted to use the following configuration
```
{
  "CHECKS": {
    "prefixes": ["fix: ", "feat: "]
  }
}
```
To check the PR but not adding any label
Just failing the CI

This is currently not supported, what do you think about adding it ?

**Comment by thehanimo** [comment]
Released [v1.3.6](https://github.com/thehanimo/pr-title-checker/releases/tag/v1.3.6)!
