### ISSUE TITLE
Any plan to upgrade to node20?

### ISSUE THREAD

**Issue by zhaoyi0113** [thehanimo/pr-title-checker#49]
I got a warning message from github action: `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: thehanimo/pr-title-checker@v1.4.1`. I wonder if there is any plan to upgrade to node20?

**Comment by thehanimo** [comment]
[v1.4.2](https://github.com/thehanimo/pr-title-checker/releases/tag/v1.4.2) uses Node v20.
