### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by FogDong** [thehanimo/pr-title-checker#8]
If the pull request is coming from a fork, it may trigger the error `HttpError: Resource not accessible by integration` when attempting to add a label.

May same to the error: actions/labeler#12

**Comment by rakesh4145** [comment]
how to check title like :-- i had made changes with JIRA  ticket 
now i want to match string if JIRA exist in  PR Title.
please suggest me regex for that

**Comment by thehanimo** [comment]
Assuming you just want to check if JIRA exists anywhere in the PR title, use: "JIRA"
